#!/bin/sh

function seed {
    node bin/auth-engine/app bin/apps/seed.json &
}

function server {
    node bin/server/app &
}

function demo {
    server; seed
    node bin/apps/todo/dbdump/dbdump &

    pushd bin/apps/todo/static
    python -m SimpleHTTPServer &
    popd
}

function test {
    server; seed
    node bin/proxy/ember/server/app &
    
    pushd bin/apps/test
    python -m SimpleHTTPServer &
    popd
}

function control_c {
    kill `jobs -p`
    exit $?
}

for i in $@
do
    $i
done

trap control_c SIGINT
while true; do read x; done